apiVersion: v1
kind: Service
metadata:
  name: mahajavapp-svc
  labels:
    app: mahajavapp
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30003
      protocol: TCP
  selector:
    app: mahajavapp
