apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahajavapp-deploy
  labels:
    app: mahajavapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mahajavapp
  template:
    metadata:
      labels:
        app: mahajavapp
    spec:
      containers:
        - name: mahajavapp-container
          image: akdhiman729/myjavaappimage:1
          ports:
            - containerPort: 8080
